lvim.plugins = {
  { "tpope/vim-surround" },
  { "mg979/vim-visual-multi" },
  { "windwp/nvim-ts-autotag" },
  -- { "JoosepAlviste/nvim-ts-context-commentstring" },
  { "windwp/nvim-autopairs" },
  -- { "nvim-lua/plenary.nvim" },
  -- { "moll/vim-bbye" },
  -- { "lunarvim/darkplus.nvim" },
  { "NvChad/nvim-colorizer.lua" },
  -- { "jose-elias-alvarez/typescript.nvim" },
  -- { "nvim-treesitter/nvim-treesitter-textobjects" },
  -- { "mfussenegger/nvim-dap-python" },
  { "andymass/vim-matchup" },
  -- { "mattn/emmet-vim" },
  -- { "hrsh7th/cmp-buffer" },
  -- { "hrsh7th/cmp-nvim-lsp" },
  -- { "hrsh7th/nvim-cmp" },
  -- { "onsails/lspkind-nvim" },
}
